<a href="https://colab.research.google.com/github/Parkseojin2001/DeepLearningZeroToAll/blob/main/lab_1_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
tf.__version__

'2.13.0'

## Hello TensorFlow!

In [5]:
hello = tf.constant("Hello, TensorFlow!")
tf.print(hello)

Hello, TensorFlow!


## Computational Graph

In [6]:
node1 = tf.constant(3.0, tf.float32)
node2 = tf.constant(4.0)

In [10]:
@tf.function
def add():
  node = tf.add(node1, node2)
  return node

In [12]:
node3 = add()

In [13]:
print("node1, node2: ", [node1, node2])
print("node3: ", node3)

node1, node2:  [<tf.Tensor: shape=(), dtype=float32, numpy=3.0>, <tf.Tensor: shape=(), dtype=float32, numpy=4.0>]
node3:  tf.Tensor(7.0, shape=(), dtype=float32)


## Variable

In [17]:
a = tf.Variable(0, dtype=tf.float32, shape = tf.TensorShape(None))
b = tf.Variable(0, dtype = tf.float32, shape = tf.TensorShape(None))

In [18]:
@tf.function
def forward(A, B):
  a.assign(A)
  b.assign(B)
  return a + b

In [21]:
print(forward(3, 4.5))
print(forward([1, 3], [2, 4]))

tf.Tensor(7.5, shape=(), dtype=float32)
tf.Tensor([3. 7.], shape=(2,), dtype=float32)


## Everything is **Tensor**

In [22]:
3

3

In [23]:
[1., 2., 3.]

[1.0, 2.0, 3.0]

In [24]:
[[1., 2., 3.], [4., 5., 6.]]

[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]

In [25]:
[[[1., 2., 3.]], [[7., 8., 9.]]]

[[[1.0, 2.0, 3.0]], [[7.0, 8.0, 9.0]]]

In [29]:
t = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [33]:
tf.shape(t)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 3], dtype=int32)>